CREATE TABLE QS_FUNCIONARIOS(
 NUMFUNC                   VARCHAR2(40)  
,NUMVINC                   VARCHAR2(40)  
,MESANOREFERENCIA          DATE          
,CATEGORIA                 VARCHAR2(20)  
,NOMECATEGORIA             VARCHAR2(60)  
,CARGAHORARIA              VARCHAR2(20)  
,NOMECARGAHORARIA          VARCHAR2(50)  
,CARGO                     VARCHAR2(40)  
,NOMECARGO                 VARCHAR2(60)  
,ESTADOCIVIL               VARCHAR2(60)  
,FAIXAETARIA               VARCHAR2(40)  
,DESCRFAIXAETARIA          VARCHAR2(60)  
,SALARIO                   NUMBER        
,FAIXASALARIAL             VARCHAR2(40)  
,DESCRFAIXASALARIAL        VARCHAR2(60)  
,GENERO                    VARCHAR2(20)  
,GRAUINSTRUCAO             VARCHAR2(20)  
,DESCRGRAUSINSTRUCAO       VARCHAR2(100) 
,GRUPOGRAUINSTRUCAO        VARCHAR2(60)  
,SETOR                     VARCHAR2(15)  
,NOMESETOR                 VARCHAR2(50)  
,NACIONALIDADE             VARCHAR2(100) 
,NATURALIDADE              VARCHAR2(3)   
,EMPRESA                   VARCHAR2(40)  
,NOMEEMPRESA               VARCHAR2(60)  
,SUBEMPRESA                VARCHAR2(40)  
,NOMESUBEMPRESA            VARCHAR2(50)  
,REFERENCIA                VARCHAR2(10)  
,REGIMEJURIDICO            VARCHAR2(20)  
,NOMEREGIMEJURIDICO        VARCHAR2(60)  
,SUBCATEGORIA              VARCHAR2(20)  
,NOMESUBCATEGORIA          VARCHAR2(60)  
,SITUACAO                  VARCHAR2(60)  
,TIPOVINCULO               VARCHAR2(20)  
,NOMETIPOVINCULO           VARCHAR2(60)  
,DTEXERC                   DATE          
,DTVAC                     DATE          
,DTAPOSENT                 DATE          
,IDADE                     VARCHAR2(40)  
,RACA                      VARCHAR2(100) 
,DEFICIENTE                VARCHAR2(1)   
,TIPODEFIC                 VARCHAR2(2)   
,DESCRTIPODEFIC            VARCHAR2(100) 
,FORMAVAC                  VARCHAR2(20)  
,DESCRFORMAVAC             VARCHAR2(60)  
,GUID_SUBEMPRESA           VARCHAR2(32)  
,CODIGONOMESETOR           VARCHAR2(68)  
,CODIGONOMECARGO           VARCHAR2(103) 
,ADMITIDO                  CHAR(1)       
,APOSENTADO                CHAR(1))
/
CREATE TABLE QS_FREQ_AFAST(    
 NUMFUNC                NUMBER(9)    
,NUMVINC                NUMBER(8)    
,MESANOREFERENCIA       DATE         
,ORIGEM                 VARCHAR2(30) 
,DTINI                  DATE         
,DTFIM                  DATE         
,QTD_DIAS               NUMBER       
,QUANTIDADE             NUMBER       
,ABERTO                 CHAR(1)      
,TIPOFREQ               VARCHAR2(20) 
,NOMETIPOFREQ           VARCHAR2(60) 
,CODFREQ                NUMBER(3)    
,NOMECODFREQ            VARCHAR2(60) 
,MNEMONICOFREQ          VARCHAR2(3))
/
CREATE TABLE QS_PAGAMENTO_CABEC( 
 FICHA             NUMBER(14)   
,NUMFUNC           NUMBER(9)    
,NUMVINC           NUMBER(8)    
,NUMPENS           NUMBER(2)    
,FOLHA             NUMBER(8)    
,MESANOFOLHA       DATE         
,TIPOFOLHA         VARCHAR2(20))
/
CREATE TABLE QS_PAGAMENTO_RUBRICAS( 
 FICHA                      NUMBER(14)   
,FATOR                      VARCHAR2(25) 
,SINAL                      NUMBER(4)    
,FAT_VANT                   NUMBER(4)    
,CLASSIFICACAORUBRICA       VARCHAR2(20) 
,MESANOREFERENCIA           DATE         
,RUBRICA                    NUMBER(8)    
,MNEMONICORUBRICA           VARCHAR2(20) 
,NOMERUBRICA                VARCHAR2(60) 
,RUB                        VARCHAR2(10) 
,TIPORUBRICA                VARCHAR2(20) 
,VALORRUBRICA               NUMBER(11,2) 
,VALORRUBRICACALC           NUMBER(11,2))
/
