create table qs_funcionarios (
    numfunc varchar(40),
    numvinc varchar(40),
    mesanoreferencia date,
    categoria varchar(20),
    nomecategoria varchar(60),
    cargahoraria varchar(20),
    nomecargahoraria varchar(50),
    cargo varchar(40),
    nomecargo varchar(60),
    estadocivil varchar(60),
    faixaetaria varchar(40),
    descrfaixaetaria varchar(60),
    salario decimal,
    faixasalarial varchar(40),
    descrfaixasalarial varchar(60),
    genero varchar(20),
    grauinstrucao varchar(20),
    descrgrausinstrucao varchar(100),
    grupograuinstrucao varchar(60),
    setor varchar(15),
    nomesetor varchar(50),
    nacionalidade varchar(100),
    naturalidade varchar(3),
    empresa varchar(40),
    nomeempresa varchar(60),
    subempresa varchar(40),
    nomesubempresa varchar(50),
    referencia varchar(10),
    regimejuridico varchar(20),
    nomeregimejuridico varchar(60),
    subcategoria varchar(20),
    nomesubcategoria varchar(60),
    situacao varchar(60),
    tipovinculo varchar(20),
    nometipovinculo varchar(60),
    dtexerc date,
    dtvac date,
    dtaposent date,
    idade varchar(40),
    raca varchar(100),
    deficiente varchar(1),
    tipodefic varchar(2),
    descrtipodefic varchar(100),
    formavac varchar(20),
    descrformavac varchar(60),
    guid_subempresa varchar(32),
    codigonomesetor varchar(68),
    codigonomecargo varchar(103),
    admitido varchar(1),
    aposentado varchar(1),
    tenantid numeric
)
/
create index idx_tenantid on qs_funcionarios(tenantid)
/

create table qs_freq_afast (
    numfunc int,
    numvinc int,
    mesanoreferencia date,
    origem varchar(30),
    dtini date,
    dtfim date,
    qtd_dias int,
    quantidade decimal,
    aberto char(1),
    tipofreq varchar(20),
    nometipofreq varchar(60),
    codfreq int,
    nomecodfreq varchar(60),
    mnemonicofreq varchar(3),
    tenantid numeric
)
/
create index idx_tenantid on qs_freq_afast(tenantid)
/